---
postgres_version: 16
postgres_port: 5432
postgres_service: postgresql-{{ postgres_version }}

# Administrative users (same for all environments)
postgres_superuser: postgres                         # Default PostgreSQL superuser
postgres_superuser_password: "your-strong-password"  # Password for postgres user
postgres_admin_user: "db_admin"                      # Custom admin user
postgres_admin_password: "your-admin-password"       # Password for admin user

# Network configuration
postgres_listen_addresses: '*'
postgres_hba_conf:
  - { type: "local", database: "all", user: "postgres", method: "peer" }
  - { type: "local", database: "all", user: "all", method: "md5" }
  - { type: "host", database: "all", user: "all", address: "127.0.0.1/32", method: "md5" }
  - { type: "host", database: "all", user: "all", address: "::1/128", method: "md5" }
  - { type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5" }
