---
# Environment-specific configuration for STAGING
postgres_data_dir: /opt/psql

# Application user and database (specific to this environment)
postgres_app_user: "app_user_stg"
postgres_app_password: "{{ vault_postgres_app_password }}"  # From vault.yml
postgres_app_user_readonly: "app_user_stg_ro"
postgres_app_password_readonly: "{{ vault_postgres_app_password_readonly }}"  # From vault.yml
postgres_app_db: "myapp_staging"
