---
postgres_repo_rpm: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"

# Pacotes para RedHat
postgres_packages_redhat:
  - postgresql16
  - postgresql16-server
  - postgresql16-contrib

# Pacotes para Debian
postgres_packages_debian:
  - postgresql-16
  - postgresql-client-16
  - postgresql-contrib

postgres_superuser: "postgres"   # Default PostgreSQL superuser
