---
- name: restart postgresql
  service:
    name: "{{ postgres_service }}"
    state: restarted

- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
