---
# Environment-specific configuration for STAGING
postgres_data_dir: /opt/psql

# Application user and database (specific to this environment)
postgres_app_user: "app_user"
postgres_app_password: "{{ vault_postgres_app_password }}"  # From vault.yml
postgres_app_user_readonly: "monitor"
postgres_app_password_readonly: "{{ vault_postgres_app_password_readonly }}"  # From vault.yml
postgres_app_db: "app_db"
